name = "store-engine"
main = "src/ecome.ts"
compatibility_date = "2024-01-01"

# 1. D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "store-db"
database_id = "05de9ca1-e7a6-450e-8826-7aadd3254499"

# 2. KV Namespace Binding
[[kv_namespaces]]
binding = "STORE_KV"
id = "9b5d81bf90e749f7b61e23b54c45815c"

# 3. R2 Bucket Binding
[[r2_buckets]]
binding = "PRODUCT_BUCKET"
bucket_name = "store-product-images"

# 4. Environment Variables
[vars]
MIDTRANS_IS_PRODUCTION = "false"
